---
    apiVersion: rbac.authorization.k8s.io/v1
    kind: Role
    metadata:
      name: deployment-creator
    rules:
      - apiGroups: ["apps"]
        resources: ["deployments"]
        verbs: ["create", "get", "update", "delete"]
---
    apiVersion: rbac.authorization.k8s.io/v1
    kind: RoleBinding
    metadata:
      name: deployment-creator-binding
    subjects:
      - kind: ServiceAccount
        name: default
        namespace: coder
    roleRef:
      kind: Role
      name: deployment-creator
      apiGroup: rbac.authorization.k8s.io

